refresh_rate: 30 seconds
appenders:
  file:
    kind: file
    path: "/home/jiri/.cache/todotxt/log.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {M} [{l}] {m}{n}"

root:
  level: info
  appenders:
    - file
